import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://eyeviewsunglasses.com'
  const now = new Date()

  // --- English blog slugs ---
  const enBlogSlugs = [
    'b2b-vs-b2c-sunglasses',
    'custom-sunglasses-packaging-ideas',
    'custom-sunglasses-packaging',
    'fda-ce-certification-sunglasses',
    'find-sunglasses-manufacturer',
    'frame-material-comparison',
    'how-sunglasses-are-made',
    'how-to-choose-sunglasses-manufacturer',
    'import-sunglasses-from-china',
    'import-sunglasses-guide',
    'negotiate-chinese-manufacturers',
    'oem-vs-odm',
    'private-label-sunglasses-guide',
    'sell-sunglasses-shopify-amazon',
    'start-sunglasses-brand',
    'sunglasses-coating-guide',
    'sunglasses-design-trends-2026',
    'sunglasses-face-shape-guide',
    'sunglasses-import-duties',
    'sunglasses-lens-guide',
    'sunglasses-lens-technology-guide',
    'sunglasses-moq-guide',
    'sunglasses-pricing-strategy',
    'sunglasses-quality-control',
    'sunglasses-startup-cost',
    'sunglasses-trade-shows-guide',
    'sustainable-sunglasses-manufacturing',
    'tr90-vs-acetate-vs-metal',
    'uv400-vs-polarized',
    'sunglasses-frame-measurements-guide',
    'sunglasses-factory-audit-checklist',
    'sunglasses-incoterms-shipping-guide',
    'wholesale-sunglasses-pricing-guide',
    'custom-sunglasses-manufacturing-process',
  ]

  // --- Spanish blog slugs ---
  const esBlogSlugs = [
    'certificacion-fda-ce-gafas',
    'comparacion-materiales-monturas',
    'control-calidad-gafas',
    'costo-iniciar-marca-gafas',
    'crear-marca-gafas',
    'empaque-personalizado-gafas',
    'encontrar-fabricante-gafas',
    'estrategia-precios-gafas',
    'fabricacion-sostenible-gafas',
    'gafas-segun-forma-rostro',
    'guia-importar-gafas',
    'guia-lentes-gafas',
    'guia-moq-gafas',
    'guia-recubrimientos-gafas',
    'oem-vs-odm',
    'tendencias-diseno-gafas-2026',
    'guia-medidas-monturas-gafas',
    'lista-auditoria-fabrica-gafas',
    'guia-incoterms-envio-gafas-sol',
    'uv400-vs-polarizado',
    'proceso-fabricacion-gafas-sol',
  ]

  // --- French blog slugs ---
  const frBlogSlugs = [
    'certification-fda-ce-lunettes',
    'comparaison-materiaux-montures',
    'controle-qualite-lunettes',
    'cout-lancement-marque-lunettes',
    'creer-marque-lunettes',
    'fabrication-lunettes-durables',
    'guide-forme-visage-lunettes',
    'guide-importation-lunettes',
    'guide-moq-lunettes',
    'guide-revetements-lunettes',
    'guide-verres-lunettes',
    'oem-vs-odm',
    'packaging-lunettes-personnalise',
    'strategie-prix-lunettes',
    'tendances-lunettes-2026',
    'trouver-fabricant-lunettes',
    'guide-mesures-montures-lunettes',
    'checklist-audit-usine-lunettes',
    'guide-incoterms-expedition-lunettes',
    'uv400-vs-polarisees',
    'processus-fabrication-lunettes-soleil',
  ]

  // --- German blog slugs ---
  const deBlogSlugs = [
    'fda-ce-zertifizierung-sonnenbrillen',
    'individuelle-sonnenbrillen-verpackung',
    'nachhaltige-sonnenbrillen-herstellung',
    'oem-vs-odm',
    'sonnenbrillen-beschichtungen-ratgeber',
    'sonnenbrillen-design-trends-2026',
    'sonnenbrillen-gesichtsform-ratgeber',
    'sonnenbrillen-glaeser-ratgeber',
    'sonnenbrillen-gruendungskosten',
    'sonnenbrillen-hersteller-finden',
    'sonnenbrillen-import-ratgeber',
    'sonnenbrillen-marke-gruenden',
    'sonnenbrillen-mindestbestellmenge-ratgeber',
    'sonnenbrillen-preisstrategie',
    'sonnenbrillen-qualitaetskontrolle',
    'uv400-vs-polarisiert',
    'sonnenbrillen-rahmenmessungen-leitfaden',
    'sonnenbrillen-fabrik-audit-checkliste',
    'sonnenbrillen-incoterms-versand-ratgeber',
    'vergleich-rahmenmaterialien',
    'sonnenbrillen-fertigungsprozess',
  ]

  // --- Portuguese blog slugs ---
  const ptBlogSlugs = [
    'certificacao-fda-ce-oculos-sol',
    'comparacao-materiais-armacoes',
    'controle-qualidade-oculos-sol',
    'criar-marca-oculos-sol',
    'custo-criar-marca-oculos-sol',
    'embalagem-personalizada-oculos-sol',
    'encontrar-fabricante-oculos-sol',
    'estrategia-precos-oculos-sol',
    'fabricacao-sustentavel-oculos-sol',
    'guia-formato-rosto-oculos',
    'guia-importacao-oculos-sol',
    'guia-lentes-oculos-sol',
    'guia-moq-oculos-sol',
    'guia-revestimentos-oculos-sol',
    'oem-vs-odm',
    'tendencias-design-oculos-2026',
    'guia-medidas-armacoes-oculos',
    'checklist-auditoria-fabrica-oculos',
    'guia-incoterms-envio-oculos',
    'uv400-vs-polarizado',
    'processo-fabricacao-oculos-sol',
  ]

  // --- Italian blog slugs ---
  const itBlogSlugs = [
    'certificazione-fda-ce-occhiali',
    'confronto-materiali-montature',
    'controllo-qualita-occhiali',
    'costi-avvio-brand-occhiali',
    'creare-brand-occhiali',
    'guida-importazione-occhiali',
    'guida-lenti-occhiali',
    'guida-moq-occhiali',
    'guida-occhiali-forma-viso',
    'guida-rivestimenti-occhiali',
    'oem-vs-odm',
    'packaging-personalizzato-occhiali',
    'produzione-sostenibile-occhiali',
    'strategia-prezzi-occhiali',
    'tendenze-design-occhiali-2026',
    'trovare-produttore-occhiali',
    'guida-misure-montature-occhiali',
    'checklist-audit-fabbrica-occhiali',
    'guida-incoterms-spedizione-occhiali',
    'uv400-vs-polarizzate',
    'processo-produzione-occhiali-sole',
  ]

  // Helper to create a sitemap entry
  const entry = (
    url: string,
    changeFrequency: 'daily' | 'weekly' | 'monthly',
    priority: number
  ) => ({
    url,
    lastModified: now,
    changeFrequency,
    priority,
  })

  return [
    // ===================== English Pages =====================
    entry(baseUrl + '/', 'daily', 1),
    entry(`${baseUrl}/about/`, 'monthly', 0.8),
    entry(`${baseUrl}/certifications/`, 'monthly', 0.8),
    entry(`${baseUrl}/contact/`, 'monthly', 0.8),
    entry(`${baseUrl}/products/`, 'weekly', 0.9),
    entry(`${baseUrl}/products/acetate/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/aviator/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/blue-light/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/cat-eye/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/eco-friendly/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/kids/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/polarized/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/round/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/sport/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/prescription/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/promotional/`, 'weekly', 0.8),
    entry(`${baseUrl}/products/sunglasses-case/`, 'weekly', 0.8),
    entry(`${baseUrl}/blog/`, 'weekly', 0.7),
    ...enBlogSlugs.map(slug => entry(`${baseUrl}/blog/${slug}`, 'monthly', 0.6)),

    // ===================== Spanish Pages =====================
    entry(`${baseUrl}/es/`, 'daily', 1),
    entry(`${baseUrl}/es/sobre-nosotros/`, 'monthly', 0.8),
    entry(`${baseUrl}/es/certificaciones/`, 'monthly', 0.8),
    entry(`${baseUrl}/es/contacto/`, 'monthly', 0.8),
    entry(`${baseUrl}/es/productos/`, 'weekly', 0.9),
    entry(`${baseUrl}/es/productos/acetato/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/aviador/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/deportivo/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/ecologico/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/luz-azul/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/ninos/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/ojo-de-gato/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/polarizado/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/redondo/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/productos/funda-gafas/`, 'weekly', 0.8),
    entry(`${baseUrl}/es/blog/`, 'weekly', 0.7),
    ...esBlogSlugs.map(slug => entry(`${baseUrl}/es/blog/${slug}`, 'monthly', 0.6)),

    // ===================== French Pages =====================
    entry(`${baseUrl}/fr/`, 'daily', 1),
    entry(`${baseUrl}/fr/a-propos/`, 'monthly', 0.8),
    entry(`${baseUrl}/fr/certifications/`, 'monthly', 0.8),
    entry(`${baseUrl}/fr/contact/`, 'monthly', 0.8),
    entry(`${baseUrl}/fr/produits/`, 'weekly', 0.9),
    entry(`${baseUrl}/fr/produits/acetate/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/aviateur/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/ecologique/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/enfants/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/lumiere-bleue/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/oeil-de-chat/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/polarise/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/rond/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/sport/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/produits/etui-lunettes/`, 'weekly', 0.8),
    entry(`${baseUrl}/fr/blog/`, 'weekly', 0.7),
    ...frBlogSlugs.map(slug => entry(`${baseUrl}/fr/blog/${slug}`, 'monthly', 0.6)),

    // ===================== German Pages =====================
    entry(`${baseUrl}/de/`, 'daily', 1),
    entry(`${baseUrl}/de/ueber-uns/`, 'monthly', 0.8),
    entry(`${baseUrl}/de/zertifizierungen/`, 'monthly', 0.8),
    entry(`${baseUrl}/de/kontakt/`, 'monthly', 0.8),
    entry(`${baseUrl}/de/produkte/`, 'weekly', 0.9),
    entry(`${baseUrl}/de/produkte/acetat/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/blaulicht/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/flieger/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/katzenaugen/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/kinder/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/polarisiert/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/rund/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/sport/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/umweltfreundlich/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/produkte/sonnenbrillen-etui/`, 'weekly', 0.8),
    entry(`${baseUrl}/de/blog/`, 'weekly', 0.7),
    ...deBlogSlugs.map(slug => entry(`${baseUrl}/de/blog/${slug}`, 'monthly', 0.6)),

    // ===================== Portuguese Pages =====================
    entry(`${baseUrl}/pt/`, 'daily', 1),
    entry(`${baseUrl}/pt/sobre-nos/`, 'monthly', 0.8),
    entry(`${baseUrl}/pt/certificacoes/`, 'monthly', 0.8),
    entry(`${baseUrl}/pt/contato/`, 'monthly', 0.8),
    entry(`${baseUrl}/pt/produtos/`, 'weekly', 0.9),
    entry(`${baseUrl}/pt/produtos/acetato/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/aviador/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/ecologico/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/esportivo/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/infantil/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/luz-azul/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/olho-de-gato/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/polarizado/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/redondo/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/produtos/capa-oculos/`, 'weekly', 0.8),
    entry(`${baseUrl}/pt/blog/`, 'weekly', 0.7),
    ...ptBlogSlugs.map(slug => entry(`${baseUrl}/pt/blog/${slug}`, 'monthly', 0.6)),

    // ===================== Italian Pages =====================
    entry(`${baseUrl}/it/`, 'daily', 1),
    entry(`${baseUrl}/it/chi-siamo/`, 'monthly', 0.8),
    entry(`${baseUrl}/it/certificazioni/`, 'monthly', 0.8),
    entry(`${baseUrl}/it/contatti/`, 'monthly', 0.8),
    entry(`${baseUrl}/it/prodotti/`, 'weekly', 0.9),
    entry(`${baseUrl}/it/prodotti/acetato/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/aviatore/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/bambini/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/ecologico/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/luce-blu/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/occhio-di-gatto/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/polarizzato/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/rotondo/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/sportivo/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/tr90/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/wayfarer/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/prodotti/fedora-occhiali/`, 'weekly', 0.8),
    entry(`${baseUrl}/it/blog/`, 'weekly', 0.7),
    ...itBlogSlugs.map(slug => entry(`${baseUrl}/it/blog/${slug}`, 'monthly', 0.6)),
  ]
}
